### PR TITLE
Adjust poll structure

### PR DESCRIPTION
**Pull request by iwz**
- Add title
- Add presenter-notes
- Fix nesting

### CODE REVIEW

**Comment by sarony** [comment]
lgtm

**Comment by teoljungberg** [comment]
Yup!

**Comment by PeterBell** [comment]
Let me fix this @iwz given new content

**Comment by PeterBell** [comment]
Hey @iwz I've merged this in, but you might want to check and fix if there are any indenting or other issues with the importer. Apologies in advance!

**Pull request merged**
