### PR TITLE
Code Block Formatting

### PR DESCRIPTION
**Pull request by crichID**
The code block formatting was applied inconsistently. I went through the modules and tried to make it more consistent throughout!

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @crichID failed the build - one complaint was line 36, column 15. I _think_ it's the back ticks.

**Comment by PeterBell** [comment]
@crichID yay! LGTM :+1:

**Comment by crichID** [comment]
@PeterBell funny that you can't start a line with the backticks but you can have them anywhere in the line without an issue. Oh well -- gonna go ahead and merge so I can make some more tweaks!

**Comment by PeterBell** [comment]
@crichID yeah - gotta love yaml :frowning:

**Pull request merged**
