### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by loranallensmith**
This PR fixes a few typos that I noticed in a few of the slides.  A few in particular I was only able to find in the `plaintext files` directory, so I'm not sure whether or not those changes will propagate to the .yml files.

It looks like Atom has made a few other changes on my behalf too.  It appears I have wiped out a lot of empty spaces in these files, so please let me know if this messes anything up.  I'm happy to cancel out this PR and make the edits through the web interface.

cc: @crichID

### CODE REVIEW

**Comment by PeterBell** [comment]
Hi @loranallensmith looks like there are a number of formatting changes which could be a problem, so might be better just to make the changes on a clean PR using the website. If you don't have the time let me know and I'll ask @timlombardo to give us a hand getting it done Monday.

**Comment by loranallensmith** [comment]
@PeterBell Thanks for taking a quick look at this.  I was worried those formatting changes might be a problem.  I'll make it a priority to get these changes PRed via the website today.  :+1:

**Comment by loranallensmith** [comment]
Going to close this one out in favor of #128 and #129 above.

**Comment by PeterBell** [comment]
Thanks @loranallensmith

**Pull request closed without merging**
