### PR TITLE
Update lab yaml structure

### PR DESCRIPTION
**Pull request by teoljungberg**
- `validation` is called `verification`

### CODE REVIEW

**Comment by iwz** [comment]
@PeterBell these changes are up to you. We can map the YML syntax into our Rails DB property names during import, or we can reformat the YML like this to match more closely to the Rails DB.

**Comment by teoljungberg** [comment]
I prefer keeping it close to the database, it makes misstakes less frequent

**Comment by teoljungberg** [comment]
I care about the names, it's less important if we use hyphens or not

**Comment by iwz** [comment]
I wonder if we should also consider changing `module` to `segment`. We couldn't use `module` in the app because it's reserved in ruby.

**Comment by teoljungberg** [comment]
Great point! Let’s do that in a separate PR, I made a card for it

**Comment by PeterBell** [comment]
Hey @iwz and @teoljungberg makes sense to match both. I've been causing trouble, committing directly on master so let me fix conflicts and merge this in

**Pull request merged**
