### PR TITLE
Creating a Free GitHub Workflow Demo for Wheelhouse

### PR DESCRIPTION
**Pull request by 1point618**
Hi @crichID,

I recently created a new Demo course, as we've discussed. @PeterBell has looked through it and given it his sign-off, so I wanted to submit a PR so that you can look at it too.

The course itself can be found [here on our staging server](https://github.wheelhouse.io/events/kLAYWLNOSq-xnC3_EQYT) if you'd like to run through it. 

Please take a look and let me know if you'd like me to change anything. We'd like this to go up as soon as possible, with the understanding that we'll continue iterating on it once it's up in front of people.

All the best,
- Adrian

### CODE REVIEW

**Comment by matthewmccullough** [comment]
> Please take a look and let me know if you'd like me to change anything. We'd like this to go up as soon as possible, with the understanding that we'll continue iterating on it once it's up in front of people.

Just wanted to lend a :sparkles: to this sentiment, as maintaining momentum of new users on the platform is critical to giving a taste test for the full, paid experience.  Let me know what I can do to help as I come up for air, hopefully by Friday (but please feel like you can beat me to that timeline).

**Comment by matthewmccullough** [comment]
CC @bonniec as you had mentioned a "free" base offering to Wheelhouse in a conversation the other day.

**Comment by matthewmccullough** [comment]
@1point618 Could you add @bonniec to this repo as well?

**Comment by 1point618** [comment]
@matthewmccullough sure thing. @johnpaulashenfelter is going to need to add her to our organization. Could you do that JP?

**Comment by crichID** [comment]
@1point618 thank you so much for getting this ready for prime time. I took a quick look through the course and I have a few small suggestions/changes:
- It feels weird to have 4 sections with 1 page each, especially given the fact we can't jump between the sections. Could we just combine it all into one section called "The Basic GitHub Workflow" or something along those lines?
- I think we need some sort of transition page at the end "Are you ready to learn more? Click here to access the full course where you will learn XYZ."
- Is there anything we can do about this "Scroll to the top and click on the "next" button to continue." Could we add a next button at the bottom of the screen?
- The demo repo has the PR banner across the top when I first log in. Can we kill that branch so it will not show up - I'm afraid it will confuse people.
  screen shot 2015-12-09 at 7 38 14 pm
- Since this is a demo, could we do something to call their attention to the labs so they can't skip over them without a warning. Or, move them to a different page? I feel like they are going to get lost or skipped at the bottom of the page.

I also have a few content edits:

> Git is a Version Control System (VCS)

"Distributed Version Control System (DVCS)

> In this course, you'll learn more about how to use these features yourself.

Should we call this a course or a demo?

> GitHub suggests a specific way of using their features in order to collaborate with your team.

This feels a little arrogant to me. Can we tone it down to something like: "The GitHub Workflow is as much about creating a culture of collaboration as it is about using a specific technology."

> When building something new in the project, this work should be done off to the side on a branch, not in the main code base.

This feels a little confusing when we haven't introduced the concept of a branch yet. 

> In the upper right, click on the button that says branch: master

The branch button is in the upper left, not the upper right.

Now that I have typed all of this, would it be easier if I just edited the files directly in the PR?

**Comment by 1point618** [comment]
Yup go ahead and make changes directly to the PR! Everything here is really good feedback.

Once you make copy changes, I'll create a couple versions of the course: 
1. Each section, an article (status quo).
2. Entire demo is 1 section.
3. Each section, an article followed by the lab steps (as per @PeterBell's suggestion).
4. Entire demo is 1 section, but lab steps are a slide following each demo.

Then we can decide which of these looks best and go with that.

---

As far as the "next on top" goes, I'll talk to @johnpaulashenfelter about it. The current layout clearly isn't optimal for the article view, but I'm hesitant to make changes to it without going through a more thought-out UX process.

**Comment by crichID** [comment]
@1point618 I made some changes to the content - hopefully I changed everything in all the right places. I noticed there were .md and .yml files for some sections and I wasn't sure which one I should be changing.

**Comment by 1point618** [comment]
@crichID  The markdown files are an old, unedited version. Did you copy/paste your changed markdown into the YML files? If so I'll need to go and make further edits to bring it in line with Peter's edits.

**Comment by crichID** [comment]
> Did you copy/paste your changed markdown into the YML files?

@1point618 yes, but I was making changes to the markdown based on what I was seeing in the module, so we may be OK.

**Comment by 1point618** [comment]
OK it went through by hand and combined both your and Peter's edits. I think the whole thing reads really well now, but do you want to read through it (just the intro file) once more to make sure?

**Comment by 1point618** [comment]
OK, so as promised I created 4 different versions of the course.
1. [Multiple Sections, Combined Labs](https://github.wheelhouse.io/events/OfmkjpnIcuLDhIYhD87J)
2. [Single Section, Combined Labs](https://github.wheelhouse.io/events/r853tzC14V_T_MUpt7cJ)
3. [Multiple Sections, Separate Labs](https://github.wheelhouse.io/events/KQeoANbTTaZJsKG5USuK)
4. [Single Section, Separate Labs](https://github.wheelhouse.io/events/FX7SSeZAaYHl2SDxcLKf)

I'd love to get everyone's feedback on the different UX paradigms here. Pinging @crichID @PeterBell @matthewmccullough @johnpaulashenfelter @chowdhury. I have opinions, but I want to hear from other people first. It may even be worth putting our top two picks in front of users :busts_in_silhouette: to get a sense of what people like most, but that can also be done once we have something _good enough_ up and running as part of the iterative process. 

Speaking of, Cynthia, what more do you need to see from us in order to give us sign-off to pull the current full course and put this up in its stead? We have a few things to do on our end as well, but I want to get sign-off from you in parallel if we can :smile:

**Comment by johnpaulashenfelter** [comment]
@crichID @1point618 I'm not comfortable adding UI to address one page -- I agree that changes to UI should be comprehensive and would avoid the one-off changes.

**Comment by matthewmccullough** [comment]
I'll defer to @crichID's thoughts, as she's been doing the most thinking about curriculum these days. :smile:

**Comment by chowdhury** [comment]
@1point618 -- thanks for this, just had a chance to run through the 4 options. 

I'm a fan of option 3 (multiple sections, separate labs). I liked the logic + flow through of the separate sections and separate labs. Felt like it was a series of bite sized chunks of learning, then a place to try it out. Didn’t like the inline labs, because of too much scrolling — so both on 1 + 2

Also, I was a little “confused” as to what the final lab was for — then i went back and read that it was to try everything out again to recap; but would liked to have seen some more messaging or direction called out separately.  I second @crichID's prior comment that there should be a clearer call out to —" ready to learn more" more explicit call to action to send them over to buy the course — the transition is a little murky as it is when there are just the 3 sentences. might be more like a button

Great stuff! :+1:

**Comment by PeterBell** [comment]
I must admit I’m with @chowdhury  in that it felt better to “turn the page” to go to the exam with the option of turning back to see the information if required - it felt cleaner and more like a “next step". That said, open to what majority of people think @1point618

**Comment by 1point618** [comment]
Wondering if @crichID has any opinions here?

**Comment by crichID** [comment]
@1point618 I prefer the single section with separate labs - however, it might be an interesting experiment if we could route 1/2 the people to single section combined labs and the other 1/2 to single section separate labs to see if there is a difference in how many people complete the labs.

**Comment by PeterBell** [comment]
Sounds like we should start by shipping the separate labs on balance @1point618 and then we can look into what it'd take to be able to direct different people to different events to test - guessing it'll be a matter of engineering priorities as to where we can get that in the backlog.

**Comment by 1point618** [comment]
Everyone's agreed about the separate labs, so let's start with that, and then we can run some manual user tests after the new year.

@crichID We can be ready to make the switch off here at early as tomorrow. The only thing we need from GH at this point is to update the text on the On-Demand tab [here](https://training.github.com/classes/developers/).

Something along the lines of the following would work:

``` markdown
Our on-demand eLearning programs offer training when and where it is most convenient for you.

* Watch short, topic-based recordings of our talented trainers from the comfort of your home or office
* Receive immediate feedback on hands-on activities
* Start and stop as often as you would like
* Budget-conscious per-student pricing

[Start learning Git and GitHub today!](https://learn.wheelhouse.io/)

Or take our free [Introduction to the GitHub Workflow](https://learn.wheelhouse.io/events/workflow).
```

I'm going to make the edits suggested to the final lab slide (linking to the purchase page) and push those, and then merge this branch.

**Comment by crichID** [comment]
@1point618 that works. I will go ahead and PR the updates to the text on training.github.com and then you can just let me know when to pull the trigger.

**Comment by 1point618** [comment]
Perfect! We'll let you know ASAP. Thanks @crichID :smile:

**Pull request merged**
