### PR TITLE
First draft CONT-CLI-06

### PR DESCRIPTION
**Pull request by crichID**

### CODE REVIEW

**Comment by crichID** [comment]
This one needs an unverified lab to clone the repo down to the desktop using the command line.

**Comment by PeterBell** [comment]
Hey @crichid merging everything in so we can start working on import and testing the basics - while the dev team and I work on that, maybe we could connect to discuss what the unverified labs should look like? I'd be tempted just to add them as labs with steps but no verifications . . .

**Comment by crichID** [comment]
> I'd be tempted just to add them as labs with steps but no verifications . . .

I think this is probably fine. At some point we may want a way for them to get help with a specific step so it seems like it is easier to build the functionality once and just have an "unverified" verification type.

**Comment by PeterBell** [comment]
Yup - agreed - really an unverified step is just long term a limitation in our system - eventually we'll install keyloggers and pwn all your p8sswrdz :)

**Comment by PeterBell** [comment]
@iwz is going to fix some syntax errors in the yml on master
Maybe we could work on adding unverified labs using PRs?

Let me create one as a template . . .

**Comment by crichID** [comment]
> eventually we'll install keyloggers and pwn all your p8sswrdz :)

Haha! I'm :eyes: you!

Let me know what he is finding in terms of syntax errors so I don't keep repeating them! I need to step away for a bit to take my son to the doctor but will be back online this afternoon.

**Comment by PeterBell** [comment]
LOL!

Will do - there will be a set of commits on master. I didn't immediately see anything wrong with your files, so I'm guessing it's equally likely either of us just messed up with extra spaces or returns or whatever, but we can create a simple guide highlighting whatever we both got wrong in the final README and eventually there will be some kind of simple validator so we can test our yml easily. Plus of course an import button you'll be able to click so you can do this on your own!

**Comment by PeterBell** [comment]
You've given  us everything we need for today. Just ping me this pm when you're about! Good luck with the doc . . .

**Pull request merged**
