### PR TITLE
Bugfixes based on user feedback from Early Access of GHfDevs.

### PR DESCRIPTION
**Pull request by 1point618**
Hi all. I'm currently going through the GHfDevs course and fixing all of the easy content issues that we've seen based on feedback from users in the course. 

I'm submitting this PR now, which is rather early, but I want to document the work as we do it. @crichID once I'm finished from my POV, I'll let you know and ask for review and feedback so that we can merge this into the master curriculum branch. Woo, GH Workflow!

### CODE REVIEW

**Comment by 1point618** [comment]
Fixes #179 
Fixes #176

**Comment by 1point618** [comment]
fixes #168

**Comment by 1point618** [comment]
fixes #164 

see also commit https://github.com/1point618/curriculum-github/commit/e675346255335b0ce276fe10c0b680c2d45bdb40 which adds to this last commit.

**Comment by 1point618** [comment]
I'd particularly like to make sure that I didn't add any bugs in that commit.

**Comment by 1point618** [comment]
fixes #182

**Comment by 1point618** [comment]
fixes #157. @johnpaulashenfelter could you confirm that having multiple "true" answers to a quiz won't blow anything up?

**Comment by johnpaulashenfelter** [comment]
@1point618 as we chatted about yesterday, yes :)

**Comment by 1point618** [comment]
Fixes #163

**Comment by 1point618** [comment]
Fixes #173 ... or at least, I hope this will.

**Comment by 1point618** [comment]
Fixes #158

**Comment by 1point618** [comment]
Fixes #161

**Comment by 1point618** [comment]
@crichID I'd love for you to look at my last commit which fixes #162, just to make sure that the new text is GH-approved :+1: . If it's good, it also fixes #167 (at least well enough for my tastes).

**Comment by 1point618** [comment]
Fixes #159

**Comment by 1point618** [comment]
OK, so as of now I have taken action on all of the content "bugs" that people have mentioned to us in our beta release of the course.

There are still some larger things that we should take action on, largely around adding some lab steps and then adding some validations in the second half of the course. However, I view that as new "features" as they'll take a lot more work to do well.

@crichID Please take a look over this when you get the chance. I'm going to wait for a :+1: from you before merging this, but I'd like to merge it ASAP. Particularly commit dbc23d3 could use some love.

Feel free to make any changes you have directly to the beta-fixes branch on my fork. 

@PeterBell ccing you in case you'd like to take a look at any of this as well.

**Comment by 1point618** [comment]
Fixes https://github.com/githubpartners/wheelhouse/issues/28

**Comment by 1point618** [comment]
OK I am merging this since I haven't heard anything about it. If any issues arise, we'll take care of them right away.

**Comment by crichID** [comment]
> I'm going to wait for a :+1: from you before merging this, but I'd like to merge it ASAP. Particularly commit dbc23d3 could use some love.

@1point618 I am curious why you would write the above and then 6 days later write: 

> OK I am merging this since I haven't heard anything about it.

With no futher attempt to re-ping myself or Joshua. Unfortunately this has been a very busy quarter for us, but we are doing our best to keep up with the pings.

**Comment by 1point618** [comment]
Hi @crichID. We had some other work we were doing that made merging this now easier. None of the data will make its way into the app until you look over it. If I handled that poorly I apologize, I thought that because all the history is still here and nothing is going into the app, it wouldn't be a problem. 

I don't think I know Joshua. Could I get an introduction? Should I be cc'ing him on all of these content overview requests?

**Comment by 1point618** [comment]
Hi @crichID,

What do you think the timeline is for getting these changes approved? We'd like to set up a new prepurchase event for GitHub, but would prefer to do it with the changes made based on the beta feedback.

Thanks!

cc/ing @johnpaulashenfelter

**Comment by 1point618** [comment]
@crichID Just checking in on the status again since it's been almost a week since the last time. The early access course closes on the 15th, and @johnpaulashenfelter and I were hoping to have this finished up and imported before then.

**Comment by crichID** [comment]
@1point618 @johnpaulashenfelter I am pinging the rest of the training team to see if we can get some :eyes: on this soonish. 

/cc @jaw6 @loranallensmith @patrickmckenna

**Comment by 1point618** [comment]
Much appreciated!

**Comment by patrickmckenna** [comment]
@crichID Since this is already merged, should we be looking at all these YAML files, or seeing how they look in Wheelhouse itself?

**Comment by 1point618** [comment]
@patrickmckenna It's all in the YAML files. We still haven't uploaded this b/c we haven't gotten sign-off. And go ahead and ignore the `markdown.md` file, that's just internal notes and won't be anywhere in the app.

---

Just so everyone is aware, due to external pressures we need to create a new course by tomorrow afternoon. @johnpaulashenfelter, @PeterBell, and I would prefer to do that by including these changes, however if we can't get sign-off in time we'll have to re-use the old course with all of these known bugs, and then we'll wait until February to use the fixed course. 

But in the interest of selling something that doesn't have known :beetle: :bee: :ant:, we'd really like to get sign-off on this. :smile:

These are all very small changes based on user feedback, so I'm hoping we can get sign-off really quickly as soon as a pair of eyes are on it. It shouldn't take more than 20-30 minutes to look through all the changes.

**Comment by crichID** [comment]
@1point618 I had a few minutes to review all of these changes and they look :+1: to me. I did not have a way to test them in the course so I will have to trust that you have done that (or will do that once the course has been created).

**Comment by 1point618** [comment]
Ah yes, I've checked this all in staging and we'll do one final run-through after importing in production.

Thanks @crichID !

**Comment by johnpaulashenfelter** [comment]
@crichID @1point618 https://learn.wheelhouse.io/events/comp is now live with this content.

**Pull request merged**
