### PR TITLE
Update to GitHub for Everyone Course

### PR DESCRIPTION
**Pull request by 1point618**
This PR represents the update to GitHub for Everyone that brings it in line with the content in GitHub for Developers.

This content has not be tested live yet, so do no merge this PR until it has been. I wanted to input the PR earlier than last time so that any changes we need to make can be discussed here. Again, **this is not ready to go live**. 

In addition, we still need to update the videos in the final three modules. @crichID, what is the status of those updates?

### CODE REVIEW

**Comment by crichID** [comment]
> We still need to update the videos in the final three modules. @crichID, what is the status of those updates?

@1point618 I am working to try to get them done ASAP. They have not been recorded but Allen has a :sparkles: template I will use to try to get them done. I would also be comfortable releasing GH4E without these modules since they cover tasks that are typically considered "project management". Given the fact we are being more literal with the Everyone piece, I think we may want to reconsider where and how these modules are presented.

**Comment by 1point618** [comment]
Sounds good, thanks @crichID. Would appreciate any eyes on the text itself, I usually introduce a few typos. 

This is an open-enrollment version of the course that anyone should be able to jump into.

https://certify-staging.herokuapp.com/events/SVkZmPR2mEGraLuBBlRA/  

/cc @timlombardo @PeterBell

**Comment by 1point618** [comment]
Oh, and my own feeling is that while they're PM-y type tasks, they're the type of thing that its good that everyone know about. Honestly, I think once they're done we could add these modules into GHfD towards the end and they'd go over well.

**Comment by crichID** [comment]
@1point618 good to know and need to know are very different. The GH for Devs class is already running at 2.5 hours. I am cautious to add any more "required" modules. We wanted to have an optional "extended modules" section at the end that people could take or ignore based on their personal interest - is there a way we can make this work? It essentially needs to be a page that lists the optional topics and they can pick the ones they want to complete.

**Comment by crichID** [comment]
@1point618 should the repo creation be working at this point? I am getting a 404 when I click on the repository link:

screenshot 2015-09-10 21 34 47

**Comment by 1point618** [comment]
I'll talk to @johnpaulashenfelter about the 404 tomorrow. There might be one of several issues going on, and I'm not able to troubleshoot it convincingly right now.

**Comment by 1point618** [comment]
I think you're right about the PM content on reflection.

We do want to move in the direction of having more smaller modules that connect to each other. How to implement that, and what those modules should be, are decisions that I think should be made strategically as we move forward. We should probably include this in the conversation that we have with @timlombardo next week. I will try to open another issue about modules and include my thoughts on them so far, but I honestly can't promise that I'll get to it before late next week b/c we have our offsite starting Sunday night.

**Comment by 1point618** [comment]
The latest commit here isn't strictly related to this PR, but these's no way yet for me to import branches to look things over. But it is good stuff, we have a bunch of new images for both fE and fD.

**Comment by 1point618** [comment]
@crichID,

I'm going to go ahead and merge this PR.

I talked it over with @PeterBell, and you and he both agree that the PM-stuff should exist in its own module. I have come over to this line of thinking, and in the interest of shipping this course on-time **I removed the PM material from GitHub for Everyone's Self Serve version**.

I also took the time to go through the course as it exists now. Much of the content has been re-used from GHfDevs, and I can't find any typos or inconsistencies in the rest. As such, I'm going to merge this PR, so that I can get a course for GitHub's new employees up and running by the end of the day. 

I'm excited to talk about further modules next week when we're all back from the off-site.

**Pull request merged**
