### PR TITLE
Fix script for reset mixed

### PR DESCRIPTION
**Pull request by crichID**
@jaw6 this PR fixes the script for the `reset --mixed` video per your concerns! When you get a chance, can you please re-record this section? I don't think you will need to do the whole audio file, just the section where it is changed, but I will defer to @loranallensmith on which one is easier.

### CODE REVIEW

**Comment by jaw6** [comment]
Will do it once I'm home! 👍

**Comment by jaw6** [comment]
I didn't have (quiet) time to record these at 🏠 this weekend. I can try to record during summit with travel mic, or record when I'm back at home on Friday.

**Comment by loranallensmith** [comment]
Not sure how I missed the ping on this Issue!  Sorry about that. :bow:  @jaw6 I think we're good with just the audio of that changed section. :metal:

**Comment by jaw6** [comment]
New :speaker:: https://github.app.box.com/files/0/f/3887654401/1/f_33654459257

Let me know if I need to record this again, or anything else!

**Comment by crichID** [comment]
With the video :ship:ed I think we are ok to merge this one in!

**Pull request merged**
